---

name: Role - python_standalone
on:
  pull_request:
    paths:
      - '.github/workflows/role-python_standalone.yml'
      - './**'
      - '!*.md'
  push:
    branches:
      - main
      - devel
    paths:
      - '.github/workflows/role-python_standalone.yml'
      - './**'
      - '!*.md'
  schedule:
    - cron: '13 13 * * 0'

jobs:
  build-docker_engine:
    name: "Role: docker_engine"
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        molecule-scenario:
          - role-python_standalone-docker
          - role-python_standalone-ec2

    uses: ./.github/workflows/_run-molecule-test.yml
    with:
      scenario: ${{ matrix.molecule-scenario }}
      python-version: ${{ matrix.python-version }}
      python-dependencies: "boto3[crt]"
    secrets: inherit

  deploy-docker_engine:
    runs-on: ubuntu-latest
    needs: build-docker_engine
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Create and Push Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          TAG_NAME=${{ github.ref_name }}
          echo "Creating tag $TAG_NAME"
          # Configure Git user
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Create the tag
          git tag "$TAG_NAME"
          # Push the tag to the repository
          git push origin "refs/tags/$TAG_NAME" --force

